### PR TITLE
Better thread handling. Adds SIGINT. Fixes #2.

### LINKED ISSUE #2: UI does not display identities correctly
When the other client sends multiple messages, the UI does not update the "Me>" tag at the bottom of the terminal. 

This leads to me having to type into the terminal which isn't aesthetically pleasing.
Snippet is as follows (the "Yeah" message should have "Me>" in front):

Them>  Hey

Them>  Whats up

Them>  U good?

Them>  s
Yeah

### PR DESCRIPTION
**Pull request by EddieDover**
I understand there are many more changes than requested for Issue #2 so if you look at my send/receive functions, you'll see how to fix #2 without needing to accept this PR.

However, this PR also shifts the code into a basic Server class, shows how to handle SIGINT (Ctrl+C) so you can quit gracefully, and shows how to implement threading without using daemon threads.

Feel free to learn from this and accept/deny this PR as you see fit. I was just looking for something to do at 3 AM 👍🏻.

### CODE REVIEW

**Comment by sundayScoop** [comment]
Glad you helped. Its super useful.
Really liked the way you fixed Issue #2 by the way. 

Now get some sleep!
Thanks!

**Comment by EddieDover** [comment]
Just keep in mind, @sundayScoop, you'll need to implement the send/receive 'fix' to the client as well. I figured leaving it for practice would be helpful. :)

**Comment by sundayScoop** [comment]
But of course @EddieDover ! 
I'm currently working on adding object classes like Connections, Main and UI to clean up the code bit for the "improve-UI" branch.
Hopefully it'll set a nice base for development and remove the need for separate client and server programs.

**Comment by sundayScoop** [comment]
@EddieDover Something a little weird is happening. I remember when I ran your fix it was great, but for some reason I'm running it now on my computer and the "Me>" line isn't going away?
Just asking in case you know why that might happen, especially since it WAS working before.
Appreciated

Code + printout (goodUI is your fix):
`python goodUI.py
Version:  1.1

Me>
Them>hello
Me>
Them>s
Me>
Them>a
Me>
Them>a`

**Comment by EddieDover** [comment]
As the code stands, it's performing as expected.
If you would like the "Me>" line to disappear if they continue sending data, then I'd take advantage of the "\r" return to move the cursor to the beginning of the line and over-write existing text when new data is sent over.

As an example, change this line in the server's receive function.
`                print("\nThem>%s\nMe> " % data.decode("utf-8"), end="" ) ## If data exists, decode and display`
to
`                print("\rThem>%s\nMe> " % data.decode("utf-8"), end="" ) ## If data exists, decode and display`
Unfortunately, this isn't a full solution since if you were already typing text and a new line comes in, you will visually see your text be overwritten but, it will secretly be in the output buffer, ready to send when you hit Enter.

To see what I mean, with the above changes, try typing half of a long sentence, then send a line over from the client.

To solve this you would have to implement the line above, and also implement some type of input buffer by taking each character pressed by the user and store it in a buffer string, re-displaying it to them when necessary, and handling backspace deletes.

It's complicates things quite a bit for such a simple program, but it's doable.

**Comment by sundayScoop** [comment]
@EddieDover I ran it with the new line and I get what you mean.
Would you recommend I set up a key listener (such as getKey or pynput) or is there a way to read individual characters from the input buffer?
Asking because I've looked and found nothing on the latter. Really considering using keylistener but it would be nice to have an alternative.

**Comment by EddieDover** [comment]
I replied via email to this, but I wasn't certain if the comment was posted to the PR, so I'll paste it here:

> Honestly, this is going to be a "try everything and see what sticks" type of situation.
> 
> The biggest issue you're going to run into is syncronizing the input buffer between the threads so you can clear and re-display already typed input after a new line comes in.
> You could try to implement a Queue since they're already setup to be multithread safe, and use sys.stdio.read(1) for the key_press thread if you really don't want to add more depencendies.
> You can probably even gut/rename your send function and do all the infinite-loop key-reading in there, and just call connection.send when the key read is a '\n'.
> 
> But you might have better results using pynput or another library. I can't really pull a solution off the top of my head, unfortunately.

**Pull request merged**
